/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto_Gestão_de_Rotina;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ThainaRibeiro
 */
public class GUI_Tarefa extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Tarefa
     */
    public GUI_Tarefa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_descricaoTarefa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descricao = new javax.swing.JTextArea();
        bt_inserirTarefa = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_deletar = new javax.swing.JButton();
        txt_pesquisar = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        lbl_gerenciamentoTarefa = new javax.swing.JLabel();
        lbl_selecionarCategoria = new javax.swing.JLabel();
        lbl_selecionarEstado = new javax.swing.JLabel();
        cb_estado = new javax.swing.JComboBox<>();
        txt_categoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_descricaoTarefa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_descricaoTarefa.setText("Descrição da Tarefa:");

        txt_descricao.setColumns(20);
        txt_descricao.setRows(5);
        jScrollPane1.setViewportView(txt_descricao);

        bt_inserirTarefa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_inserirTarefa.setText("Inserir nova Tarefa");
        bt_inserirTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inserirTarefaActionPerformed(evt);
            }
        });

        bt_editar.setText("Editar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_deletar.setText("Deletar");
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });

        bt_pesquisar.setText(" 🔎 ");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        lbl_gerenciamentoTarefa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_gerenciamentoTarefa.setText("Gerenciamento Tarefa");

        lbl_selecionarCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_selecionarCategoria.setText("Categoria:");

        lbl_selecionarEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_selecionarEstado.setText("Selecionar Estado:");

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Em andamento", "Concluído" }));
        cb_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_estadoActionPerformed(evt);
            }
        });

        txt_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_categoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_gerenciamentoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_pesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_descricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_deletar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_inserirTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_selecionarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_selecionarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(266, 266, 266))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_gerenciamentoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_pesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editar)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_selecionarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_selecionarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbl_descricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_deletar)
                    .addComponent(bt_inserirTarefa))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_inserirTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inserirTarefaActionPerformed
        // TODO add your handling code here:
        try {

            String categoria = txt_categoria.getText();
            String estado = (String) cb_estado.getSelectedItem();//converter combobox para string 
            String descricao = txt_descricao.getText();

            FileWriter arq = new FileWriter("c:\\arqu\\tarefa.txt");///informa o caminho do arquivo criado, arq é a pasta ,usuario e senha nome do arquivo dentro de arq
            PrintWriter gravarArq = new PrintWriter(arq);
            gravarArq.printf(categoria, estado, descricao);
            arq.close();//Fecha o arquivo
            JOptionPane.showMessageDialog(null, "Arquivo Salvo com sucesso!!");

            //salvo no banco de dados
            String driverName = "com.mysql.jdbc.Driver";//nome do tradutor

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "204.216.145.129";    //caminho do servidor do BD

            String mydatabase = "progb2024";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "progb2024";        //nome de um usuário de seu BD      

            String password = "progb2024";      //sua senha de acesso

            Connection conn = DriverManager.getConnection(url, username, password);

            Statement stmt = conn.createStatement();//inserir na caixa de texto do banco

            //ResultSet rs = stmt.executeQuery( "SELECT nome FROM cliente WHERE color = 'blue'" );
            String idcategoria = txt_categoria.getText();
            estado = (String) cb_estado.getSelectedItem();//converter combobox para string 
            descricao = txt_descricao.getText();
            stmt.execute("INSERT INTO thaina_tarefa(idcategoria, estado,descricao) VALUES('" + idcategoria + "','" + estado + "','" + descricao + "');"); ///preparaco da insercao do registro
            conn.close();
            System.out.println("Salvo com Sucesso");

        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }


    }//GEN-LAST:event_bt_inserirTarefaActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        // TODO add your handling code here:
        try {
            String categoria = txt_categoria.getText();
            String estado = (String) cb_estado.getSelectedItem();//converter combobox para string 
            String descricao = txt_descricao.getText();

        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }

    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:
        try {
            String categoria = txt_categoria.getText();
            String estado = (String) cb_estado.getSelectedItem();//converter combobox para string 
            String descricao = txt_descricao.getText();

            String driverName = "com.mysql.jdbc.Driver";

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "204.216.145.129";    //caminho do servidor do BD

            String mydatabase = "progb2024";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false";

            String username = "progb2024";        //nome de um usuário de seu BD      

            String password = "progb2024";      //sua senha de acesso

            Connection conn = DriverManager.getConnection(url, username, password);

            Statement stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT * FROM thaina_tarefa");

            while (rs.next()) {
                int idTarefa = rs.getInt("idtarefa");
                int idCategoria = rs.getInt("idcategoria");
                descricao = rs.getString("descricao");
                estado = rs.getString("estado");

                System.out.println("id Tarefa=" + idTarefa + "  id Categoria=" + idCategoria + "   descricao=" + descricao + "   estado=" + estado);
            }
            conn.close();
        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }

    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void cb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_estadoActionPerformed

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed
        // TODO add your handling code here:
        try {
            String categoria = txt_categoria.getText();
            String estado = (String) cb_estado.getSelectedItem();//converter combobox para string 
            String descricao = txt_descricao.getText();;

        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }


    }//GEN-LAST:event_bt_deletarActionPerformed

    private void txt_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_categoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Tarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Tarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Tarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Tarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Tarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_deletar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_inserirTarefa;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_descricaoTarefa;
    private javax.swing.JLabel lbl_gerenciamentoTarefa;
    private javax.swing.JLabel lbl_selecionarCategoria;
    private javax.swing.JLabel lbl_selecionarEstado;
    private javax.swing.JTextField txt_categoria;
    private javax.swing.JTextArea txt_descricao;
    private javax.swing.JTextField txt_pesquisar;
    // End of variables declaration//GEN-END:variables
}
