/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto_Gestão_de_Rotina;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ThainaRibeiro
 */
public class GUI_RecuperacaoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form GUI_RecuperacaoUsuario
     */
    public GUI_RecuperacaoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bt_editar = new javax.swing.JButton();
        txt_pesquisar = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        lbl_confirmar = new javax.swing.JLabel();
        bt_enviarCodigo = new javax.swing.JButton();
        lbl_digiteSenha = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        lbl_digiteCodigo = new javax.swing.JLabel();
        txt_senha = new javax.swing.JTextField();
        bt_salvar = new javax.swing.JButton();
        bt_desfazer = new javax.swing.JButton();
        lbl_cadastrarPessoa = new javax.swing.JLabel();
        cb_tipoEnvio = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_editar.setText("Editar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_pesquisar.setText(" 🔎 ");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        lbl_confirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_confirmar.setText("Como deseja confirmar identidade?");

        bt_enviarCodigo.setText("Enviar Código");
        bt_enviarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarCodigoActionPerformed(evt);
            }
        });

        lbl_digiteSenha.setText("Digite a nova Senha:");

        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });

        lbl_digiteCodigo.setText("Digite seu código:");

        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_desfazer.setText("Desfazer");
        bt_desfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_desfazerActionPerformed(evt);
            }
        });

        lbl_cadastrarPessoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_cadastrarPessoa.setText("Recuperar Conta");

        cb_tipoEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Email", "Sms" }));
        cb_tipoEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_pesquisar)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_desfazer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_digiteCodigo)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lbl_digiteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_senha))))
                                .addGap(111, 111, 111))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cb_tipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_enviarCodigo)
                                .addGap(131, 131, 131))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(lbl_cadastrarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl_cadastrarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisar))
                .addGap(18, 18, 18)
                .addComponent(bt_editar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_enviarCodigo))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_digiteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_digiteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_desfazer))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        // TODO add your handling code here:

        try {
            String tipoEnvio = (String) cb_tipoEnvio.getSelectedItem();//converter combobox para string 
            String codigo = txt_codigo.getText();
            String senha = txt_senha.getText();

        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }

    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:
        try {
            String tipoEnvio = (String) cb_tipoEnvio.getSelectedItem();//converter combobox para string 
            String codigo = txt_codigo.getText();
            String senha = txt_senha.getText();

            String driverName = "com.mysql.jdbc.Driver";

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "204.216.145.129";    //caminho do servidor do BD

            String mydatabase = "progb2024";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false";

            String username = "progb2024";        //nome de um usuário de seu BD      

            String password = "progb2024";      //sua senha de acesso

            Connection conn = DriverManager.getConnection(url, username, password);

            Statement stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT * FROM thaina_recuperacao");

            while (rs.next()) {
                int idRecuperacao = rs.getInt("idrecuperacao");
                int idPessoa = rs.getInt("idpessoa");
                senha = rs.getString("senha");
                codigo = rs.getString("codigo");
                tipoEnvio = rs.getString("tipoenvio");
                String data = rs.getString("data");
                String horario = rs.getString("horario");

                System.out.println("id Recuperacao=" + idRecuperacao + "  id pessoa=" + idPessoa + "   senha=" + senha + "   codigo=" + codigo + "   tipo de envio=" + tipoEnvio + "   data=" + data + "   horario=" + horario);
            }
            conn.close();
        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void bt_enviarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarCodigoActionPerformed
        // TODO add your handling code here:
        try {
            String tipoEnvio = (String) cb_tipoEnvio.getSelectedItem();//converter combobox para string 
            String codigo = txt_codigo.getText();
            String senha = txt_senha.getText();

        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }

    }//GEN-LAST:event_bt_enviarCodigoActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        // TODO add your handling code here:
        try {

            String tipoEnvio = (String) cb_tipoEnvio.getSelectedItem();//converter combobox para string 
            String codigo = txt_codigo.getText();
            String senha = txt_senha.getText();

            FileWriter arq = new FileWriter("c:\\arqu\\recuperacao.txt");///informa o caminho do arquivo criado, arq é a pasta ,usuario e senha nome do arquivo dentro de arq
            PrintWriter gravarArq = new PrintWriter(arq);
            gravarArq.printf(tipoEnvio, codigo, senha);
            arq.close();//Fecha o arquivo
            JOptionPane.showMessageDialog(null, "Arquivo Salvo com sucesso!!");

            //salvo no banco de dados
            String driverName = "com.mysql.jdbc.Driver";//nome do tradutor

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "204.216.145.129";    //caminho do servidor do BD

            String mydatabase = "progb2024";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "progb2024";        //nome de um usuário de seu BD      

            String password = "progb2024";      //sua senha de acesso

            Connection conn = DriverManager.getConnection(url, username, password);

            Statement stmt = conn.createStatement();//inserir na caixa de texto do banco

            //ResultSet rs = stmt.executeQuery( "SELECT nome FROM cliente WHERE color = 'blue'" );
            tipoEnvio = (String) cb_tipoEnvio.getSelectedItem();//converter combobox para string 
            codigo = txt_codigo.getText();
            senha = txt_senha.getText();
            stmt.execute("INSERT INTO thaina_recuperacao(tipoenvio , codigo ,senha ) VALUES('" + tipoEnvio + "','" + codigo + "','" + senha + "');"); ///preparaco da insercao do registro
            conn.close();
            System.out.println("Salvo com Sucesso");

        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }

    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_desfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_desfazerActionPerformed
        // TODO add your handling code here:
        try {
            String tipoEnvio = (String) cb_tipoEnvio.getSelectedItem();//converter combobox para string 
            String codigo = txt_codigo.getText();
            String senha = txt_senha.getText();

        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }
    }//GEN-LAST:event_bt_desfazerActionPerformed

    private void cb_tipoEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoEnvioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_tipoEnvioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_RecuperacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_RecuperacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_RecuperacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_RecuperacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_RecuperacaoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_desfazer;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_enviarCodigo;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JComboBox<String> cb_tipoEnvio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_cadastrarPessoa;
    private javax.swing.JLabel lbl_confirmar;
    private javax.swing.JLabel lbl_digiteCodigo;
    private javax.swing.JLabel lbl_digiteSenha;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_pesquisar;
    private javax.swing.JTextField txt_senha;
    // End of variables declaration//GEN-END:variables
}
