/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto_Gestão_de_Rotina;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ThainaRibeiro
 */
public class GUI_Login extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Login
     */
    public GUI_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_usuario = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        bt_entrar = new javax.swing.JButton();
        bt_esqueciMinhaSenha = new javax.swing.JButton();
        lbl_login = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        txt_pesquisar = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_usuario.setText("Usuário:");

        lbl_senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_senha.setText("Senha:");

        bt_entrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_entrar.setText("Entrar");
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });

        bt_esqueciMinhaSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_esqueciMinhaSenha.setText("Esqueci minha senha");
        bt_esqueciMinhaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_esqueciMinhaSenhaActionPerformed(evt);
            }
        });

        lbl_login.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_login.setText("           Login");

        txt_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senhaActionPerformed(evt);
            }
        });

        txt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisarActionPerformed(evt);
            }
        });

        bt_pesquisar.setText(" 🔎 ");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_esqueciMinhaSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_entrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbl_login, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_pesquisar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_login, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesquisar)
                    .addComponent(bt_pesquisar))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_entrar)
                    .addComponent(bt_esqueciMinhaSenha))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed
        // TODO add your handling code here:

        try {
            String usuario = txt_usuario.getText();
            String senha = txt_senha.getText();
            FileWriter arq = new FileWriter("c:\\arqu\\usuario e senha.txt");///informa o caminho do arquivo criado, arq é a pasta ,usuario e senha nome do arquivo dentro de arq
            PrintWriter gravarArq = new PrintWriter(arq);
            gravarArq.printf(usuario, senha);
            arq.close();//Fecha o arquivo
            JOptionPane.showMessageDialog(null, "Arquivo Salvo com sucesso!!");

            //salvo no banco de dados
            String driverName = "com.mysql.jdbc.Driver";//nome do tradutor

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "204.216.145.129";    //caminho do servidor do BD

            String mydatabase = "progb2024";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "progb2024";        //nome de um usuário de seu BD      

            String password = "progb2024";      //sua senha de acesso

            Connection conn = DriverManager.getConnection(url, username, password);

            Statement stmt = conn.createStatement();//inserir na caixa de texto do banco

            //ResultSet rs = stmt.executeQuery( "SELECT nome FROM cliente WHERE color = 'blue'" );
            usuario = txt_usuario.getText();
            senha = txt_senha.getText();

            stmt.execute("INSERT INTO thaina_login(usuario , senha ) VALUES('" + usuario + "','" + senha + "' );"); ///preparaco da insercao do registro
            conn.close();
            System.out.println("Salvo com Sucesso");

        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }
    }//GEN-LAST:event_bt_entrarActionPerformed

    private void txt_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaActionPerformed

    private void bt_esqueciMinhaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_esqueciMinhaSenhaActionPerformed
        // TODO add your handling code here:
        try {
            String usuario = txt_usuario.getText();
            String senha = txt_senha.getText();
        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }

    }//GEN-LAST:event_bt_esqueciMinhaSenhaActionPerformed

    private void txt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesquisarActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:
        try {
            String usuario = txt_usuario.getText();
            String senha = txt_senha.getText();

            String driverName = "com.mysql.jdbc.Driver";

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "204.216.145.129";    //caminho do servidor do BD

            String mydatabase = "progb2024";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false";

            String username = "progb2024";        //nome de um usuário de seu BD

            String password = "progb2024";      //sua senha de acesso

            Connection conn = DriverManager.getConnection(url, username, password);

            Statement stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT * FROM thaina_login");

            while (rs.next()) {
                usuario = rs.getString("usuario");
                senha = rs.getString("senha");
                int id = rs.getInt("ID");

                System.out.println("usuario=" + usuario + "senha=" + senha + "id=" + id);
            }
            conn.close();
        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_entrar;
    private javax.swing.JButton bt_esqueciMinhaSenha;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTextField txt_pesquisar;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
