/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto_Gestão_de_Rotina;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ThainaRibeiro
 */
public class GUI_Notificacao extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Notificacao
     */
    public GUI_Notificacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        txt_pesquisar = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        lbl_gerenciamentoNotificacao = new javax.swing.JLabel();
        bt_enviarNotificacao = new javax.swing.JButton();
        lbl_tarefa = new javax.swing.JLabel();
        lbl_selecionarEnvio = new javax.swing.JLabel();
        bt_cancelar = new javax.swing.JButton();
        lbl_dataHorario = new javax.swing.JLabel();
        txt_data = new javax.swing.JTextField();
        txt_horario = new javax.swing.JTextField();
        bt_editar = new javax.swing.JButton();
        cb_tipoenvio = new javax.swing.JComboBox<>();
        txt_tarefa = new javax.swing.JTextField();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lazer", "Estudo", "Trabalho", "Compromissos" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisarActionPerformed(evt);
            }
        });

        bt_pesquisar.setText(" 🔎 ");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        lbl_gerenciamentoNotificacao.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_gerenciamentoNotificacao.setText("Gerenciamento de Notificações");

        bt_enviarNotificacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_enviarNotificacao.setText("Enviar Notificação");
        bt_enviarNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarNotificacaoActionPerformed(evt);
            }
        });

        lbl_tarefa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_tarefa.setText(" NºTarefa:");

        lbl_selecionarEnvio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_selecionarEnvio.setText("Selecionar Envio:");

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        lbl_dataHorario.setText("Selecionar Data e Horário:");

        txt_data.setText("          /     / ");

        txt_horario.setText("        :");

        bt_editar.setText("Editar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        cb_tipoenvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Email", "Sms", "" }));
        cb_tipoenvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoenvioActionPerformed(evt);
            }
        });

        txt_tarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tarefaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_selecionarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(169, 169, 169)
                                        .addComponent(bt_cancelar)
                                        .addGap(52, 52, 52)
                                        .addComponent(bt_enviarNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb_tipoenvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_gerenciamentoNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_pesquisar)))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_tarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txt_tarefa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dataHorario)
                                .addGap(18, 18, 18)
                                .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(263, 263, 263))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pesquisar)
                            .addComponent(bt_pesquisar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addComponent(lbl_gerenciamentoNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(bt_editar)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_selecionarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipoenvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dataHorario)
                    .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancelar)
                    .addComponent(bt_enviarNotificacao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_enviarNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarNotificacaoActionPerformed
        // TODO add your handling code here:
        try {
            String tarefa = txt_tarefa.getText();//nao guarda numero inteiro para salvar arquivo
            String horario = txt_horario.getText();
            String data = txt_data.getText();
            String tipoenvio = (String) cb_tipoenvio.getSelectedItem();
            FileWriter arq = new FileWriter("c:\\arqu\\notificacao.txt");///informa o caminho do arquivo criado, arq é a pasta ,usuario e senha nome do arquivo dentro de arq
            PrintWriter gravarArq = new PrintWriter(arq);
            gravarArq.printf(tarefa, horario, data, tipoenvio);
            arq.close();//Fecha o arquivo
            JOptionPane.showMessageDialog(null, "Arquivo Salvo com sucesso!!");

            //salvo no banco de dados
            String driverName = "com.mysql.jdbc.Driver";//nome do tradutor

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "204.216.145.129";    //caminho do servidor do BD

            String mydatabase = "progb2024";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "progb2024";        //nome de um usuário de seu BD      

            String password = "progb2024";      //sua senha de acesso

            Connection conn = DriverManager.getConnection(url, username, password);

            Statement stmt = conn.createStatement();//inserir na caixa de texto do banco

            //ResultSet rs = stmt.executeQuery( "SELECT nome FROM cliente WHERE color = 'blue'" );
            int idtarefa = Integer.parseInt(txt_tarefa.getText());//banco aceita todos os tipos
            horario = txt_horario.getText();
            data = txt_data.getText();
            tipoenvio = (String) cb_tipoenvio.getSelectedItem();

            stmt.execute("INSERT INTO thaina_notificacao(idtarefa , horario , data, tipoenvio ) VALUES('" + idtarefa + "','" + horario + "','" + data + "','" + tipoenvio + "');"); ///preparaco da insercao do registro
            conn.close();
            System.out.println("Salvo com Sucesso");

        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }
    }//GEN-LAST:event_bt_enviarNotificacaoActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        // TODO add your handling code here:
        try {
            String tarefa = txt_tarefa.getText();
            String data = txt_data.getText();
            String horario = txt_data.getText();

        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        // TODO add your handling code here:
        try {
            String tarefa = txt_tarefa.getText();
            String data = txt_data.getText();
            String horario = txt_data.getText();

        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }
    }//GEN-LAST:event_bt_editarActionPerformed

    private void txt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesquisarActionPerformed

    private void cb_tipoenvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoenvioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_tipoenvioActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:
        try {
            String idtarefa = txt_tarefa.getText();
            String data = txt_data.getText();
            String horario = txt_horario.getText();
            String tipoenvio = (String) cb_tipoenvio.getSelectedItem();

            String driverName = "com.mysql.jdbc.Driver";

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "204.216.145.129";    //caminho do servidor do BD

            String mydatabase = "progb2024";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false";

            String username = "progb2024";        //nome de um usuário de seu BD      

            String password = "progb2024";      //sua senha de acesso

            Connection conn = DriverManager.getConnection(url, username, password);

            Statement stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT * FROM thaina_notificacao");

            while (rs.next()) {
                int id = rs.getInt("id");
                int idpessoa = rs.getInt("idpessoa");
                idtarefa = rs.getString("idtarefa");
                data = rs.getString("data");
                horario = rs.getString("horario");
                String enviado = rs.getString("enviado");
                tipoenvio = rs.getString("tipoenvio");

                System.out.println("ID= " + id + "   ID Pessoa= " + idpessoa + "    ID tarefa= " + idtarefa + "   data= " + data + "    horario= " + horario + "enviado= " + enviado + "   tipo de envio= " + tipoenvio);
            }
            conn.close();
        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        } catch (Exception erroGenerico) {
            System.out.println("erro generico = " + erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro " + erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null, "Ocorreu um erro");
        }
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // CarregarTarefas()
    }//GEN-LAST:event_formWindowOpened

    private void txt_tarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tarefaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Notificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Notificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Notificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Notificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Notificacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_enviarNotificacao;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cb_tipoenvio;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel lbl_dataHorario;
    private javax.swing.JLabel lbl_gerenciamentoNotificacao;
    private javax.swing.JLabel lbl_selecionarEnvio;
    private javax.swing.JLabel lbl_tarefa;
    private javax.swing.JTextField txt_data;
    private javax.swing.JTextField txt_horario;
    private javax.swing.JTextField txt_pesquisar;
    private javax.swing.JTextField txt_tarefa;
    // End of variables declaration//GEN-END:variables

    /* private void CarregarTarefas() {//metodo
        try {
            cb_selecionar.removeAllItems();//função remover todos itens (1,2,3,4) para ficar vazio
            
            String driverName = "com.mysql.jdbc.Driver";
 
            Class.forName(driverName);
 
            // Configurando a nossa conexão com um banco de dados//
            String serverName = "204.216.145.129";    //caminho do servidor do BD
 
            String mydatabase = "progb2024";        //nome do seu banco de dados
 
            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false";
 
            String username = "progb2024";        //nome de um usuário de seu BD      
 
            String password = "progb2024";      //sua senha de acesso
 
            Connection conn = DriverManager.getConnection(url, username, password);
 
            Statement stmt = conn.createStatement();
 
            ResultSet rs = stmt.executeQuery("SELECT * FROM thaina_tarefa");
 
            while (rs.next()) {
                cb_selecionar.addItem(rs.getString("descricao"));
            }
            conn.close();
        }  catch (Exception erroGenerico)
        {
            System.out.println("erro generico = "+erroGenerico.getLocalizedMessage());
            System.out.println("Querido usuário temos um erro "+erroGenerico.fillInStackTrace());//fillInStackTrace informa o tipo de erro
            JOptionPane.showMessageDialog(null,"Ocorreu um erro");
        }
        
    }*/
}
